# Generated by Django 5.2 on 2025-04-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaute', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
