# Generated by Django 5.2 on 2025-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaute', '0003_delete_product_remove_produit_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('maquillage', 'Maquillage'), ('cheveux', 'Soins Cheveux'), ('peau', 'Soins Peau'), ('parfum', 'Parfum')], default='maquillage', max_length=50),
            preserve_default=False,
        ),
    ]
