# Generated by Django 5.2 on 2025-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beaute', '0004_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('cosmetics', 'Cosmetics'), ('makeup', 'Makeup'), ('powder', 'Powder'), ('lotions', 'Lotions'), ('lipstick', 'Lipstick'), ('mascara', 'Mascara')], max_length=50),
        ),
    ]
